name: Build

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        
      - name: Test
        run: rm -rf build && mkdir -p build && cd build && cmake .. && make -j4 


